version: "3.9"
services:
  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    container_name: "sqlserver"
    expose:
    - 1433
    environment:
      SA_PASSWORD: "P@ssw0rd"
      ACCEPT_EULA: "Y"
    volumes:
    - sqlvolume:/var/opt/mssql
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "$$SA_PASSWORD" -Q "SELECT 1" -b || exit 1
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s

  search:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    container_name: elasticsearch
    restart: on-failure
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    healthcheck:
      test: curl -s http://localhost:9200 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5
    ulimits:
      memlock:
        soft: -1
        hard: -1
    expose:
    - 9200

  logserver:
    image: docker.elastic.co/kibana/kibana:7.12.0
    container_name: kibana
    depends_on:
    - elasticsearch
    ports:
    - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200

  cache:
    image: "redis"
    container_name: "rediscache"
    expose:
    - 6379

  webapi:
    build: "."
    container_name: "tendermanagement-api"
    restart: on-failure
    ports:
    - 8000:80
    depends_on:
    - db
    - cache
    - logserver
    environment:
      DOTNET_ENVIRONMENT: "Container"

volumes:
  sqlvolume:
    external: true
